#!/usr/bin/env bash
# Write a Bash script that configures an Ubuntu server with the below requirements.

tmpfile=$(mktemp)

sed 's/127\.0\.0\.1/127.0.0.2/' /etc/hosts > "$tmpfile"
echo "8.8.8.8 facebook.com" >> "$tmpfile"

sudo cp "$tmpfile" /etc/hosts
rm "$tmpfile"
